project:
  type: website
  output-dir: ../docs

website:
  title: Analysis of "Basic Girl Stocks" and their Presence in Stock Subreddits
  sidebar:
    background: primary
    logo: "images/bd-logo.png"
    pinned: true
    align: center
    style: docked
    contents:
      - href: index.qmd
        text: Introduction
      - href: eda.qmd
        text: Exploratory Data Analysis
      - href: nlp.qmd
        text: Natural Language Processing
      - href: ml.qmd
        text: Machine Learning
      - href: conclusion.qmd
        text: Conclusion
  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var author.name >}}] <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

format:
  html:
    theme: united

