# Conclusion

This project explored how often four subreddits (wallstreetbets, investing, stock, traders) received submissions that mentioned "basic girl stocks." It also explored general themes across, sentiment of, and engagement with these posts, using natural language processing techniques. We were interested in how submissions and comments in these forums discuss these "basic girl" stocks and how submission and comment engagement scores, sentiment, and discussion content vary when posts discuss "basic girl" stocks versus other stocks or topics.

We found that the daily number of submissions and that mention a "basic girl stock" and associated comments were generally stable over time. We then examined the distribution of the lengths of all the comments. Most comments (over 700,000) had under 200 characters. There were some outliers with over 1000 characters. We used the SparkNLP sentiment analysis tools to develop a pipeline that pulled in our documents and analyzed the sentiment of each comment, providing a resulting positive/negative/neutral. When looking at submissions, approximately two-thirds of the posts were identified as having positive sentiment and approximately one-third was identified as having negative sentiment. Very few submissions had neutral sentiment results. Similarly, the overwhelming majority of comments were classified as having either positive or negative sentiment. Very few comments had neutral sentiment.

We applied topic modeling to four different groups of text to identify overall themes in specific discussions. The topics generated for submissions that mentioned "basic girl" stocks included terms representing "basic girl" companies like Netflix and Meta (Facebook), as well as terms describing success, holding stocks, and the Metaverse. Topics for the comments on these submissions also focused on the company, Meta, but differed from the topics generated for the submissions in that they included more terms related to bots, money, and the stock market more broadly.

The machine learning aspect of this project gave us some insight into working with stock data, as stock discussions can be incredibly volatile and can shift focus quickly and without warning as stock market news spreads. The machine learning aspect of this project highlighted the challenges in making accurate predictions about Reddit submissions that discuss "basic girl" stocks. The varying sentiments associated with different types of submissions, coupled with the similarity in engagement metrics across submissions that mentioned the different stocks, made it difficult to create models that performed better than random guessing.

### Next Steps

Insights gained from these analyses can inform future research and modeling efforts in this field. With more time, we would attempt more machine learning models and employ additional hyperparameter tuning steps in an effort to increase prediction accuracy. We would also explore text prediction methods to see if the submission and comment content could aid in predicting information about the submissions and comments. Lastly, we would expand on our natural language processing work by creating additional interesting visuals like word clouds to better display our findings.

